In [10]:
# import useful libraries for data preprocessing
import numpy as np
import pandas as pd
import seaborn as sns

In [11]:
# change the current path for referencing
import sys
sys.path.append('../')

# import functions from python(.py) files
from scripts.dataGeneration import getRandomWord, count_FP, count_TP

In [12]:
import os
os.path.abspath(os.getcwd())

'/mnt/c/Users/12428/Documents/GitHub/MAT_180_ML_Projects/cecilia_nicole_wei/notebooks'

In [13]:
# read in data from the dataset
df_10000_9 = pd.read_excel(r"../data/10000_9_dataset.xlsx")

df_10000_9

Unnamed: 0                                braid  \
0              0    [-2, 2, -3, 3, -2, -2, 1, -3, -3]   
1              1    [3, -1, -2, 2, -2, -2, -3, 3, -1]   
2              2        [1, -3, 2, 3, 2, 2, 1, 2, -1]   
3              3    [-1, -1, 1, -1, 3, -2, -1, 3, -2]   
4              4      [1, -3, -2, 3, 1, 1, 2, -1, -3]   
...          ...                                  ...   
9995        9995      [2, 1, -1, 2, -3, 1, -3, 1, -3]   
9996        9996    [-1, 2, -1, 1, -1, 1, -1, -2, -1]   
9997        9997     [1, -3, -1, -3, -2, -3, 2, 2, 3]   
9998        9998     [-2, 2, 3, -2, 3, 2, -1, -2, -3]   
9999        9999  [-2, -1, -2, -2, 2, -3, -1, -1, -2]   

                                              free_part  \
0     {(-11, -4): 1, (-9, -4): 1, (-7, -2): 2, (-5, ...   
1     {(-11, -4): 1, (-9, -4): 1, (-7, -2): 2, (-5, ...   
2          {(1, 0): 1, (3, 0): 1, (5, 2): 1, (9, 3): 1}   
3     {(-11, -4): 1, (-9, -3): 1, (-7, -3): 1, (-7, ...   
4     {(-5, -2): 1, (-3, -2): 1, (-1, 0): 2, (1, 0):...   
...                                                 ...   
9995  {(-7, -3): 1, (-3, -2): 1, (-3, -1): 2, (-1, 0...   
9996  {(-6, -2): 1, (-4, -2): 1, (-2, 0): 1, (0, 0): 1}   
9997     {(-3, 0): 1, (-1, 0): 3, (1, 0): 3, (3, 0): 1}   
9998                            {(-1, 0): 1, (1, 0): 1}   
9999  {(-15, -5): 1, (-11, -4): 1, (-11, -3): 1, (-7...   

                                           torsion_part  
0                                                    {}  
1                                                    {}  
2                                      {(7, 3): {2: 1}}  
3     {(-9, -3): {2: 1}, (-7, -2): {2: 1}, (-5, -1):...  
4                                                    {}  
...                                                 ...  
9995  {(-5, -2): {2: 1}, (-1, 0): {2: 2}, (3, 2): {2...  
9996                                                 {}  
9997                                                 {}  
9998                                                 {}  
9999              {(-13, -4): {2: 1}, (-9, -2): {2: 1}}  

[10000 rows x 4 columns]

In [14]:
# vectorize the eval function
ev = np.vectorize(eval)

# count free_part of the dataset
ff = np.vectorize(count_FP)
df_10000_9['total_num_FP'] = ff(ev(df_10000_9['free_part']))

# count torsion_part of the dataset
ft = np.vectorize(count_TP)
df_10000_9['total_num_TP'] = ft(ev(df_10000_9['torsion_part']))

In [15]:
# view the dataset with added columns of total_num_FP and total_num_TP
df_10000_9

Unnamed: 0                                braid  \
0              0    [-2, 2, -3, 3, -2, -2, 1, -3, -3]   
1              1    [3, -1, -2, 2, -2, -2, -3, 3, -1]   
2              2        [1, -3, 2, 3, 2, 2, 1, 2, -1]   
3              3    [-1, -1, 1, -1, 3, -2, -1, 3, -2]   
4              4      [1, -3, -2, 3, 1, 1, 2, -1, -3]   
...          ...                                  ...   
9995        9995      [2, 1, -1, 2, -3, 1, -3, 1, -3]   
9996        9996    [-1, 2, -1, 1, -1, 1, -1, -2, -1]   
9997        9997     [1, -3, -1, -3, -2, -3, 2, 2, 3]   
9998        9998     [-2, 2, 3, -2, 3, 2, -1, -2, -3]   
9999        9999  [-2, -1, -2, -2, 2, -3, -1, -1, -2]   

                                              free_part  \
0     {(-11, -4): 1, (-9, -4): 1, (-7, -2): 2, (-5, ...   
1     {(-11, -4): 1, (-9, -4): 1, (-7, -2): 2, (-5, ...   
2          {(1, 0): 1, (3, 0): 1, (5, 2): 1, (9, 3): 1}   
3     {(-11, -4): 1, (-9, -3): 1, (-7, -3): 1, (-7, ...   
4     {(-5, -2): 1, (-3, -2): 1, (-1, 0): 2, (1, 0):...   
...                                                 ...   
9995  {(-7, -3): 1, (-3, -2): 1, (-3, -1): 2, (-1, 0...   
9996  {(-6, -2): 1, (-4, -2): 1, (-2, 0): 1, (0, 0): 1}   
9997     {(-3, 0): 1, (-1, 0): 3, (1, 0): 3, (3, 0): 1}   
9998                            {(-1, 0): 1, (1, 0): 1}   
9999  {(-15, -5): 1, (-11, -4): 1, (-11, -3): 1, (-7...   

                                           torsion_part  total_num_FP  \
0                                                    {}             8   
1                                                    {}             8   
2                                      {(7, 3): {2: 1}}             4   
3     {(-9, -3): {2: 1}, (-7, -2): {2: 1}, (-5, -1):...            12   
4                                                    {}             8   
...                                                 ...           ...   
9995  {(-5, -2): {2: 1}, (-1, 0): {2: 2}, (3, 2): {2...            16   
9996                                                 {}             4   
9997                                                 {}             8   
9998                                                 {}             2   
9999              {(-13, -4): {2: 1}, (-9, -2): {2: 1}}             6   

      total_num_TP  
0                0  
1                0  
2                1  
3                5  
4                0  
...            ...  
9995             4  
9996             0  
9997             0  
9998             0  
9999             2  

[10000 rows x 6 columns]

In [16]:
# drop the Unnamed: 0 column
df_10000_9 = df_10000_9.drop(columns=['Unnamed: 0'])

# store the dataset wtih total number of free_group and torsion_group
df_10000_9.to_csv(r'../data/10000_9.csv')

Polynomial Features: [1,x,x**2]
[ 1.  8. 64.]
Polynomial Features: [1,x,x**2]
[ 1.  4. 16.]


(0.7760218826695919, 0.7733002448256452)

In [93]:
# degree=3 Polynomial Regression
polynomial_features= PolynomialFeatures(degree=3)
X_poly_train_deg3 = polynomial_features.fit_transform(X_train)
print('Polynomial Features: [1,x,x**2,x**3]')
print(X_poly_train_deg3[0])

X_poly_test_deg3 = polynomial_features.fit_transform(X_test)
print('Polynomial Features: [1,x,x**2,x**3]')
print(X_poly_test_deg3[0])

polyreg = LinearRegression().fit(X_poly_train_deg3, y_train)
polyreg.score(X_poly_train_deg3,y_train), polyreg.score(X_poly_test_deg3,y_test)

Polynomial Features: [1,x,x**2,x**3]
[  1.   8.  64. 512.]
Polynomial Features: [1,x,x**2,x**3]
[ 1.  4. 16. 64.]


(0.8087584562425066, 0.8108776478818277)

In [94]:
# degree=4 Polynomial Regression
polynomial_features= PolynomialFeatures(degree=4)
X_poly_train_deg4 = polynomial_features.fit_transform(X_train)
print('Polynomial Features: [1,x,x**2,x**3,x**4]')
print(X_poly_train_deg4[0])

X_poly_test_deg4 = polynomial_features.fit_transform(X_test)
print('Polynomial Features: [1,x,x**2,x**3,x**4]')
print(X_poly_test_deg4[0])

polyreg = LinearRegression().fit(X_poly_train_deg4, y_train)
polyreg.score(X_poly_train_deg4,y_train), polyreg.score(X_poly_test_deg4,y_test)

Polynomial Features: [1,x,x**2,x**3,x**4]
[1.000e+00 8.000e+00 6.400e+01 5.120e+02 4.096e+03]
Polynomial Features: [1,x,x**2,x**3,x**4]
[  1.   4.  16.  64. 256.]


(0.8156807700699248, 0.8122638927953894)

In [106]:
# degree=8 Polynomial Regression
polynomial_features= PolynomialFeatures(degree=8)
X_poly_train_deg8 = polynomial_features.fit_transform(X_train)
print('Polynomial Features: [1,x,x**2,x**3,x**4,...]')
print(X_poly_train_deg8[0])

X_poly_test_deg8 = polynomial_features.fit_transform(X_test)
print('Polynomial Features: [1,x,x**2,x**3,x**4,...]')
print(X_poly_test_deg8[0])

polyreg = LinearRegression().fit(X_poly_train_deg8, y_train)
polyreg.score(X_poly_train_deg8,y_train), polyreg.score(X_poly_test_deg8,y_test)

Polynomial Features: [1,x,x**2,x**3,x**4,...]
[1.0000000e+00 8.0000000e+00 6.4000000e+01 5.1200000e+02 4.0960000e+03
 3.2768000e+04 2.6214400e+05 2.0971520e+06 1.6777216e+07]
Polynomial Features: [1,x,x**2,x**3,x**4,...]
[1.0000e+00 4.0000e+00 1.6000e+01 6.4000e+01 2.5600e+02 1.0240e+03
 4.0960e+03 1.6384e+04 6.5536e+04]


(0.834907426770338, 0.8293480049628128)

In [105]:
# degree=9 Polynomial Regression (BEST DEGREE TO STOP AT)
polynomial_features= PolynomialFeatures(degree=9)
X_poly_train_deg9 = polynomial_features.fit_transform(X_train)
print('Polynomial Features: [1,x,x**2,x**3,x**4,...]')
print(X_poly_train_deg9[0])

X_poly_test_deg9 = polynomial_features.fit_transform(X_test)
print('Polynomial Features: [1,x,x**2,x**3,x**4,...]')
print(X_poly_test_deg9[0])

polyreg = LinearRegression().fit(X_poly_train_deg9, y_train)
polyreg.score(X_poly_train_deg9,y_train), polyreg.score(X_poly_test_deg9,y_test)

Polynomial Features: [1,x,x**2,x**3,x**4,...]
[1.00000000e+00 8.00000000e+00 6.40000000e+01 5.12000000e+02
 4.09600000e+03 3.27680000e+04 2.62144000e+05 2.09715200e+06
 1.67772160e+07 1.34217728e+08]
Polynomial Features: [1,x,x**2,x**3,x**4,...]
[1.00000e+00 4.00000e+00 1.60000e+01 6.40000e+01 2.56000e+02 1.02400e+03
 4.09600e+03 1.63840e+04 6.55360e+04 2.62144e+05]


(0.8382640243793316, 0.8334184865907028)

In [95]:
# degree=10 Polynomial Regression
polynomial_features= PolynomialFeatures(degree=10)
X_poly_train_deg10 = polynomial_features.fit_transform(X_train)
print('Polynomial Features: [1,x,x**2,x**3,x**4,...]')
print(X_poly_train_deg10[0])

X_poly_test_deg10 = polynomial_features.fit_transform(X_test)
print('Polynomial Features: [1,x,x**2,x**3,x**4,...]')
print(X_poly_test_deg10[0])

polyreg = LinearRegression().fit(X_poly_train_deg10, y_train)
polyreg.score(X_poly_train_deg10,y_train), polyreg.score(X_poly_test_deg10,y_test)

Polynomial Features: [1,x,x**2,x**3,x**4,...]
[1.00000000e+00 8.00000000e+00 6.40000000e+01 5.12000000e+02
 4.09600000e+03 3.27680000e+04 2.62144000e+05 2.09715200e+06
 1.67772160e+07 1.34217728e+08 1.07374182e+09]
Polynomial Features: [1,x,x**2,x**3,x**4,...]
[1.000000e+00 4.000000e+00 1.600000e+01 6.400000e+01 2.560000e+02
 1.024000e+03 4.096000e+03 1.638400e+04 6.553600e+04 2.621440e+05
 1.048576e+06]


(0.8233658926809484, 0.8170114959997536)

In [104]:
# degree=11 Polynomial Regression
polynomial_features= PolynomialFeatures(degree=11)
X_poly_train_deg11 = polynomial_features.fit_transform(X_train)
print('Polynomial Features: [1,x,x**2,x**3,x**4,...]')
print(X_poly_train_deg11[0])

X_poly_test_deg11 = polynomial_features.fit_transform(X_test)
print('Polynomial Features: [1,x,x**2,x**3,x**4,...]')
print(X_poly_test_deg11[0])

polyreg = LinearRegression().fit(X_poly_train_deg11, y_train)
polyreg.score(X_poly_train_deg11,y_train), polyreg.score(X_poly_test_deg11,y_test)

Polynomial Features: [1,x,x**2,x**3,x**4,...]
[1.00000000e+00 8.00000000e+00 6.40000000e+01 5.12000000e+02
 4.09600000e+03 3.27680000e+04 2.62144000e+05 2.09715200e+06
 1.67772160e+07 1.34217728e+08 1.07374182e+09 8.58993459e+09]
Polynomial Features: [1,x,x**2,x**3,x**4,...]
[1.000000e+00 4.000000e+00 1.600000e+01 6.400000e+01 2.560000e+02
 1.024000e+03 4.096000e+03 1.638400e+04 6.553600e+04 2.621440e+05
 1.048576e+06 4.194304e+06]


(0.823383248806407, 0.8163111119283295)

In [103]:
# degree=12 Polynomial Regression
polynomial_features= PolynomialFeatures(degree=12)
X_poly_train_deg12 = polynomial_features.fit_transform(X_train)
print('Polynomial Features: [1,x,x**2,x**3,x**4,...]')
print(X_poly_train_deg12[0])

X_poly_test_deg12 = polynomial_features.fit_transform(X_test)
print('Polynomial Features: [1,x,x**2,x**3,x**4,...]')
print(X_poly_test_deg12[0])

polyreg = LinearRegression().fit(X_poly_train_deg12, y_train)
polyreg.score(X_poly_train_deg12,y_train), polyreg.score(X_poly_test_deg12,y_test)

Polynomial Features: [1,x,x**2,x**3,x**4,...]
[1.00000000e+00 8.00000000e+00 6.40000000e+01 5.12000000e+02
 4.09600000e+03 3.27680000e+04 2.62144000e+05 2.09715200e+06
 1.67772160e+07 1.34217728e+08 1.07374182e+09 8.58993459e+09
 6.87194767e+10]
Polynomial Features: [1,x,x**2,x**3,x**4,...]
[1.0000000e+00 4.0000000e+00 1.6000000e+01 6.4000000e+01 2.5600000e+02
 1.0240000e+03 4.0960000e+03 1.6384000e+04 6.5536000e+04 2.6214400e+05
 1.0485760e+06 4.1943040e+06 1.6777216e+07]


(0.8156448070779628, 0.8077636025920225)

In [102]:
# degree=15 Polynomial Regression
polynomial_features= PolynomialFeatures(degree=15)
X_poly_train_deg15 = polynomial_features.fit_transform(X_train)
print('Polynomial Features: [1,x,x**2,x**3,x**4,...]')
print(X_poly_train_deg15[0])

X_poly_test_deg15 = polynomial_features.fit_transform(X_test)
print('Polynomial Features: [1,x,x**2,x**3,x**4,...]')
print(X_poly_test_deg15[0])

polyreg = LinearRegression().fit(X_poly_train_deg15, y_train)
polyreg.score(X_poly_train_deg15,y_train), polyreg.score(X_poly_test_deg15,y_test)

Polynomial Features: [1,x,x**2,x**3,x**4,...]
[1.00000000e+00 8.00000000e+00 6.40000000e+01 5.12000000e+02
 4.09600000e+03 3.27680000e+04 2.62144000e+05 2.09715200e+06
 1.67772160e+07 1.34217728e+08 1.07374182e+09 8.58993459e+09
 6.87194767e+10 5.49755814e+11 4.39804651e+12 3.51843721e+13]
Polynomial Features: [1,x,x**2,x**3,x**4,...]
[1.00000000e+00 4.00000000e+00 1.60000000e+01 6.40000000e+01
 2.56000000e+02 1.02400000e+03 4.09600000e+03 1.63840000e+04
 6.55360000e+04 2.62144000e+05 1.04857600e+06 4.19430400e+06
 1.67772160e+07 6.71088640e+07 2.68435456e+08 1.07374182e+09]


(0.5561200693352634, 0.5640550656689641)

In [101]:
# degree=20 Polynomial Regression
polynomial_features= PolynomialFeatures(degree=20)
X_poly_train_deg20 = polynomial_features.fit_transform(X_train)
print('Polynomial Features: [1,x,x**2,x**3,x**4,...]')
print(X_poly_train_deg20[0])

X_poly_test_deg20 = polynomial_features.fit_transform(X_test)
print('Polynomial Features: [1,x,x**2,x**3,x**4,...]')
print(X_poly_test_deg20[0])

polyreg = LinearRegression().fit(X_poly_train_deg20, y_train)
polyreg.score(X_poly_train_deg20,y_train), polyreg.score(X_poly_test_deg20,y_test)

Polynomial Features: [1,x,x**2,x**3,x**4,...]
[1.00000000e+00 8.00000000e+00 6.40000000e+01 5.12000000e+02
 4.09600000e+03 3.27680000e+04 2.62144000e+05 2.09715200e+06
 1.67772160e+07 1.34217728e+08 1.07374182e+09 8.58993459e+09
 6.87194767e+10 5.49755814e+11 4.39804651e+12 3.51843721e+13
 2.81474977e+14 2.25179981e+15 1.80143985e+16 1.44115188e+17
 1.15292150e+18]
Polynomial Features: [1,x,x**2,x**3,x**4,...]
[1.00000000e+00 4.00000000e+00 1.60000000e+01 6.40000000e+01
 2.56000000e+02 1.02400000e+03 4.09600000e+03 1.63840000e+04
 6.55360000e+04 2.62144000e+05 1.04857600e+06 4.19430400e+06
 1.67772160e+07 6.71088640e+07 2.68435456e+08 1.07374182e+09
 4.29496730e+09 1.71798692e+10 6.87194767e+10 2.74877907e+11
 1.09951163e+12]


(0.3445403734540968, 0.3186285939212903)

In [96]:
# degree=100 Polynomial Regression
polynomial_features= PolynomialFeatures(degree=100)
X_poly_train_deg100 = polynomial_features.fit_transform(X_train)
print('Polynomial Features: [1,x,x**2,x**3,x**4,...]')
print(X_poly_train_deg100[0])

X_poly_test_deg100 = polynomial_features.fit_transform(X_test)
print('Polynomial Features: [1,x,x**2,x**3,x**4,...]')
print(X_poly_test_deg100[0])

polyreg = LinearRegression().fit(X_poly_train_deg100, y_train)
polyreg.score(X_poly_train_deg100,y_train), polyreg.score(X_poly_test_deg100,y_test)

Polynomial Features: [1,x,x**2,x**3,x**4,...]
[1.00000000e+00 8.00000000e+00 6.40000000e+01 5.12000000e+02
 4.09600000e+03 3.27680000e+04 2.62144000e+05 2.09715200e+06
 1.67772160e+07 1.34217728e+08 1.07374182e+09 8.58993459e+09
 6.87194767e+10 5.49755814e+11 4.39804651e+12 3.51843721e+13
 2.81474977e+14 2.25179981e+15 1.80143985e+16 1.44115188e+17
 1.15292150e+18 9.22337204e+18 7.37869763e+19 5.90295810e+20
 4.72236648e+21 3.77789319e+22 3.02231455e+23 2.41785164e+24
 1.93428131e+25 1.54742505e+26 1.23794004e+27 9.90352031e+27
 7.92281625e+28 6.33825300e+29 5.07060240e+30 4.05648192e+31
 3.24518554e+32 2.59614843e+33 2.07691874e+34 1.66153499e+35
 1.32922800e+36 1.06338240e+37 8.50705917e+37 6.80564734e+38
 5.44451787e+39 4.35561430e+40 3.48449144e+41 2.78759315e+42
 2.23007452e+43 1.78405962e+44 1.42724769e+45 1.14179815e+46
 9.13438523e+46 7.30750819e+47 5.84600655e+48 4.67680524e+49
 3.74144419e+50 2.99315535e+51 2.39452428e+52 1.91561943e+53
 1.53249554e+54 1.22599643e+55 9.807971

(0.0383740841347292, 0.009173822876757609)

In [ ]:
braid	free_part	torsion_part	row_1_num_FP	row_2_num_FP	row_3_num_FP	/.../	row_n_num_FP	total_num_TP

In [9]:
# using what we wrote from Homework_2_Computational
from numpy import linalg as LA

# to complete problem 3, fill in the following with your code
def J(X,y,v):
    ######################### your code goes here ########################
    rowx = len(X)
    ones = np.ones([rowx,1])
    x_hat = np.concatenate((ones,X), axis = 1)
    print(x_hat.shape)
    print(v.shape)
    print(y.shape)
    J = LA.norm(x_hat@v-y)**2
    return (1/rowx)*J

def DJ(X,y,v):
    ######################### your code goes here ########################
    rowx = len(X)
    ones = np.ones([rowx,1])
    x_hat = np.concatenate((ones,X), axis = 1)
    gradient = x_hat.T@x_hat@v-x_hat.T@y
    return (2/rowx)*gradient

# to complete problem 4, fill in the following with your code
def GD_linreg_improved(X,y,epsilon,max_iters=10000): 
    ######################### your code goes here ########################
    rowx = len(X)
    colx = len(X[0])
    ones = np.ones([rowx,1])
    x_hat = np.concatenate((ones,X), axis = 1)
    v = np.zeros([colx+1,1])
    H = (2/rowx)*x_hat.T@x_hat
    costs = [J(X,y,v)]
    for i in range(max_iters):
        alpha = (DJ(X,y,v).T@DJ(X,y,v))/(DJ(X,y,v).T@H@DJ(X,y,v))
        v = v-alpha*DJ(X,y,v)
        costs.append(J(X,y,v))
        if i % 100 == 0:
            print(f'after {i} steps the cost is {costs[i]}')
        if abs(costs[i] - costs[i-1])<epsilon:
            break
    print(f'after {i} steps the cost is {costs[i]}')
    return v,costs

# Choose the value of epsilon (and max_iters if you want)
epsilon = .02
max_iters = 10000

# Using only 1000 data for X
X_hw_test = X[0:1000]
y_hw_test = y[0:1000]

# Run the second order gradient descent algorithm (no input needed)
# You should find a similar value of v and cost (hopefully improved)
v,costs = GD_linreg_improved(X_hw_test,y_hw_test,epsilon)
print(v)

# plot for fun (test and compare with graph in problem5)
plt.plot(costs)
plt.xlabel('number of iterations')
plt.ylabel('Cost J(v)')
plt.show()

(1000, 2)
(2, 1)
(1000,)
(1000, 2)
(2, 2)
(1000,)


ValueError: operands could not be broadcast together with shapes (1000,2) (1000,) 