# <center> Python/Numpy Introduction</center>

Note: you can learn much more than is offered in this gentle introduction by clicking the `help` tab above and reading through the documentation for Python and Numpy.

In this notebook, we will explore basic operations in python and then introduce matrices as arrays using the library numpy. Run the code cell by cell by clicking in the interior of the cell and pressing `shift`+`return`. 

# Numbers, Functions, Strings, Lists

The equal sign in python acts as variable assignment, so for example the following code block assigns the value `5` to the variable `n`

In [9]:
n = 5

Calling the variable `n` will print its value

In [10]:
n

5

We can reassign the current value plus one by calling the following

In [11]:
n = n + 1
n

6

Alternatively we can use the shorthand `n += 1` to increment the value of `n` by `1` so after calling this cell the value should be `7`.

In [12]:
n+=1
n

7

To check if two values are equal, one can use the `==` command:

In [29]:
n==7

True

In [30]:
n==8

False

Define a function in Python using the `def` keyword as follows. We will add one to the input and square it. Note that in Python, exponentiation is done using `**`. If an output is desired, it should be written after the keyword `return`.

In [16]:
def function_name(input_name):
    result = (input_name + 1)**2
    return result

Let us now call our function on the input `7`, so we expect an output of $(7+1)^2 = 8 ^2 = 64$

In [17]:
function_name(7)

64

Python `strings` are created by using either single quotes or double quotes (these are treated identically)

In [18]:
string1 = 'this is a string'
string2 = "let's use double quotes so we can use apostrophes in our strings"

Strings can be printed using the print function

In [19]:
print(string1)
print(string2)

this is a string
let's use double quotes so we can use apostrophes in our strings


We can use `f-strings` to embed variables in strings as follows:

In [23]:
number = 18
print(f"the number is {number}")

the number is 18


In [24]:
number += 1
print(f"the number is {number}")

the number is 19


Python `lists` can be created by entering Python objects separated by commas between square brackets

In [25]:
list1 = [1,2,3,4,5]

Python lists are 0-indexed so on can access the first element by calling:

In [26]:
list1[0]

1

In [27]:
list1[1]

2

The last element can be called using the argument `-1`

In [28]:
list1[-1]

5

A common list we will use is created using the range function. `range(n)` returns the list with `n` elements `0,1,...,n-1`

In [33]:
l = range(5)

In [34]:
l[0]

0

In [35]:
l[-1]

4

To iterate over the elements of a list, use a `for loop`:

In [36]:
for i in range(7):
    print(i)

0
1
2
3
4
5
6


We can use `range(a,b)` to start the range at `a`

In [37]:
for i in range(3,10):
    print(i)

3
4
5
6
7
8
9


We can use `range(a,b,s)` to skip by units of `s`

In [38]:
for i in range(3,10,2):
    print(i)

3
5
7
9


Recall the formula $$\sum_{i=1}^n i = \frac{n(n+1)}{2}$$
Let's check that this holds true

In [47]:
def left_side(n):
    result = 0
    for i in range(n+1): #using n+1 because the range ends at n
        result += i
    return result

def right_side(n):
    return n*(n+1)//2 #we can use / or // for division. / returns a float and // return an integer (we want an integer)

In [52]:
left_side(151)

11476

In [51]:
right_side(151)

11476

# Numpy Arrays

We will often be using the numpy library (imported as np meaning we use np in our code blocks instead of numpy). The most important numpy object for us is the `array` object. We will mostly use arrays to represent vectors and matrices. These are 1 and 2 dimensional numpy arrays respectively. Recursively defined, an `n` dimensional numpy array is constructed as a list of `n-1` dimensional numpy arrays. Let us start with `n=1`, that is, with vectors.

In [53]:
# run this cell to import numpy as the shorthand np
import numpy as np

To construct a 1 dimensional numpy array, simply call `np.array` on a list of numbers.

In [60]:
v = np.array([1,2,3,4])
w = np.array([1,0,1,3])

In [61]:
v

array([1, 2, 3, 4])

In [62]:
w

array([1, 0, 1, 3])

numpy arrays can be added componentwise as vectors using the `+` command and scalar multiplied using the `*` command:

In [63]:
v+w

array([2, 2, 4, 7])

In [64]:
2*v

array([2, 4, 6, 8])

Matrices are represented as 2-dimensional numpy arrays. By our previous definition, that means they should be constructed as lists of 1-dimensional numpy arrays. Each list in the list is treated as a row of the matrix.

In [67]:
A = np.array([[1,2,3],[2,3,4],[4,5,6]])
A

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

Matrices of the same size can be added and scalar multiplied componentwise just like 1-dimensional arrays:

In [81]:
B = np.array([[1,0,1],[2,1,3],[0,3,6]])
B

array([[1, 0, 1],
       [2, 1, 3],
       [0, 3, 6]])

In [69]:
A+B

array([[ 2,  2,  4],
       [ 4,  4,  7],
       [ 4,  8, 12]])

In [70]:
2*A

array([[ 2,  4,  6],
       [ 4,  6,  8],
       [ 8, 10, 12]])

Matrices can be multiplied with the `@` command:

In [80]:
A@B

array([[ 5, 11, 25],
       [ 8, 15, 35],
       [14, 23, 55]])

One can use `*` but this will give a different multiplication (pointwise)

In [82]:
A*B

array([[ 1,  0,  3],
       [ 4,  3, 12],
       [ 0, 15, 36]])

From a 2-dimensional array, one can obtain its rows and columns as 1-dimensional arrays using `A[i,:]` and `A[:,j]` which are treated as we treat $a_{i,*}$ and $a_{*,j}$ as we defined in class. Recall that python is a 0-indexed language, so the first row is `A[0,:]` and the first column is `A[:,0]`.

In [71]:
A[1,:]

array([2, 3, 4])

In [72]:
A[0,:]

array([1, 2, 3])

Another way to view vectors would be as either $n\times 1$ or $1\times n$ matrices. This may be preferable if we wish to distinguish between row and column vectors

In [85]:
v1 = np.array([[1,2,3]])
v1

array([[1, 2, 3]])

In [99]:
v2 = np.array([[1],[2],[3]])
v2

array([[1],
       [2],
       [3]])

We can try multiplying vectors by matrices in both forms and see if they agree

In [100]:
v3 = np.array([1,2,3])
v3

array([1, 2, 3])

First we multiply the $3\times 3$ matrix `A` by `v1`:

In [101]:
A@v1

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 3)

This throws an error message because $A\in\mathbb{R}^{3\times 3}$ and $v_1\in\mathbb{R}^{1\times 3}$.

Now we try multiplying `A` by `v2` which should work because the dimensions match

In [102]:
A@v2

array([[14],
       [20],
       [32]])

Next we see how python interprets a product of a 2-dimensional array with a 1-dimensional array of appropriate dimension

In [103]:
A@v3

array([14, 20, 32])

The product is computed correctly and output as a 1-dimensional numpy array

What about multiplying the vector on the left? Explain the following results.

In [104]:
v1@A

array([[17, 23, 29]])

In [105]:
v2@A

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 1)

In [106]:
v3@A

array([17, 23, 29])

We see that python interprets the 1-dimensional array as either a row vector or as a column vector. It chooses whatever makes sense in the current situation.